// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @param {string} key
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function Scan(key) {
    let $resultPromise = /** @type {any} */($Call.ByID(2957224028, key));
    return $resultPromise;
}
